"""Build deterministic LÖVE image fonts for the 240x216 HGSS canvas."""

from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
MOD = ROOT / "mod" / "kanto_gear"
SOURCES = Path(__file__).resolve().parent / "sources"


def glyphs() -> str:
    value = "".join(chr(code) for code in range(32, 127)) + "×→←▲▼"
    for path in MOD.rglob("*.lua"):
        value += "".join(
            char for char in path.read_text(encoding="utf-8") if ord(char) >= 128
        )
    return "".join(dict.fromkeys(value))


def supported(source: Path, value: str) -> str:
    font = TTFont(source)
    cmap: set[int] = set()
    for table in font["cmap"].tables:
        cmap.update(table.cmap)
    return "".join(char for char in value if ord(char) in cmap)


def render(source: Path, size: int, value: str, output: Path) -> None:
    font = ImageFont.truetype(source, size, layout_engine=ImageFont.Layout.BASIC)
    widths = [max(1, round(font.getlength(char))) for char in value]
    ascent, descent = font.getmetrics()
    image = Image.new("RGBA", (sum(widths) + len(value) + 1, ascent + descent))
    draw = ImageDraw.Draw(image)
    x = 0
    for char, width in zip(value, widths, strict=True):
        draw.point((x, 0), fill=(255, 0, 255, 255))
        draw.text((x + 1, 0), char, font=font, fill=(255, 255, 255, 255))
        x += width + 1
    draw.point((x, 0), fill=(255, 0, 255, 255))
    image.save(output, optimize=True)


def main() -> None:
    main_source = SOURCES / "hgss_pixel.ttf"
    small_source = SOURCES / "hgss_small.ttf"
    value = supported(main_source, supported(small_source, glyphs()))
    (MOD / "hgss_font_glyphs.lua").write_text(
        "-- Generated by tools/hgss_font_atlas/generate.py.\n"
        f"return [=[{value}]=]\n",
        encoding="utf-8",
        newline="\n",
    )
    render(main_source, 10, value, MOD / "hgss_font.png")
    render(small_source, 11, value, MOD / "hgss_small_font.png")
    render(main_source, 20, value, MOD / "hgss_large_font.png")


if __name__ == "__main__":
    main()
