-- Generated by tools/hgss_font_atlas/generate.py.
return [=[ !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~×→←▲▼…é·¥ÄÖÜÀÂÇÁÈÉÊËÍÎÏÓÔÚÙÛŸÑ¿¡°ºäöüßàâçèêëîïôùûÿáíóúñ]=]
